### ISSUE TITLE
html: the src of img tag has issue 

### ISSUE THREAD

**Issue by lingllqs** [brianhuster/live-preview.nvim#131]
the actual url: http://localhost:5500/02_img.html
![图片](https://github.com/user-attachments/assets/9b070669-140c-4aba-85b6-96c2740d5d7e)
i can not acccess image via a relative path (../images/2.webp)
```text
1. <img src="../images/2.webp" alt=""> # do not work
2. <img src="./1.webp" alt=""> # work
```

**Comment by brianhuster** [comment]
I have addressed the root of the issue. Will have it fixed today or tomorrow (GMT+7)

**Comment by brianhuster** [comment]
I have changed the default webroot to `:pwd`. which should fix the error. Please update the plugin

**Comment by lingllqs** [comment]
![图片](https://github.com/user-attachments/assets/0c3372ed-a90c-4c87-8dfb-441befab814f)
still wrong, is there i haven't done it right?

**Comment by brianhuster** [comment]
If you don't mind, can you send me the repo link, so I can test it?

**Comment by brianhuster** [comment]
First, please run `:checkhealth livepreview`, it may help you troubleshoot the problem. 

If that doesn't help, and if you don't mind, can you send me steps to reproduce the error? For example, can you send me a smaller version of your web repo?

**Comment by brianhuster** [comment]
With the newest version, the webroot is, by default, set to the current working directory of you Neovim. Run `:pwd` to see your current directory. 

Also, make sure you use the default config or the option `dynamic_webroot` is set to `false`.

**Comment by lingllqs** [comment]
![图片](https://github.com/user-attachments/assets/4daf37ef-17f7-41aa-b794-369b8ac56e27)
I only have this plugin now,but the issue still appear  here is my configuration:(the single file) ( ~/.config/nvim/init.lua)
-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
	local lazyrepo = "https://github.com/folke/lazy.nvim.git"
	local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
	if vim.v.shell_error ~= 0 then
		vim.api.nvim_echo({
			{ "Failed to clone lazy.nvim:\n", "ErrorMsg" },
			{ out, "WarningMsg" },
			{ "\nPress any key to exit..." },
		}, true, {})
		vim.fn.getchar()
		os.exit(1)
	end
end
vim.opt.rtp:prepend(lazypath)

-- Make sure to setup `mapleader` and `maplocalleader` before
-- loading lazy.nvim so that mappings are correct.
-- This is also a good place to setup other settings (vim.opt)
vim.g.mapleader = " "
vim.g.maplocalleader = "\\"

require("lazy").setup({
	'brianhuster/live-preview.nvim',
	dependencies = {'brianhuster/autosave.nvim'}, -- Not required, but recomended for autosaving
	opts = {
		commands = {
			start = 'LivePreview', -- Command to start the live preview server and open the default browser.
			stop = 'StopPreview', -- Command to stop the live preview. 
		},
		port = 5500, -- Port to run the live preview server on.
		browser = 'default', -- Terminal command to open the browser for live-previewing (eg. 'firefox', 'flatpak run com.vivaldi.Vivaldi'). By default, it will use the default browser.
		dynamic_root = false, -- If true, the plugin will set the root directory to the previewed file's directory. If false, the root directory will be the current working directory (`:lua print(vim.uv.cwd())`).
	},
})

**Comment by brianhuster** [comment]
So you are not in the right current working directory. The root of your web project is `~/workspace/programs/practice/html`, but `:pwd` shows that your current working is `~/workspace/programs/practice/html/demo`. Your current working directory should be the **same** as your web project. 

To solve this,please run `:cd ~/workspace/programs/practice/html` or `:cd ..` in your Nvim cmdline. 

If your problem is solved, please close this issue!
