### ISSUE TITLE
bug: Doesn't reload correctly

### ISSUE THREAD

**Issue by BlackCherryCat** [brianhuster/live-preview.nvim#274]
### Did you read the documentation and check existing issues?

- [x] I have read all the documentations ([README](https://github.com/brianhuster/live-preview.nvim), [`:h livepreview`](https://github.com/brianhuster/live-preview.nvim/blob/main/doc/livepreview.txt), [Wiki](https://github.com/brianhuster/live-preview.nvim/wiki))
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the [existing issues](https://github.com/brianhuster/live-preview.nvim/issues) and [closed issues](https://github.com/brianhuster/live-preview.nvim/issues?q=is%3Aissue+is%3Aclosed) issues

### Neovim version (nvim -v)

0.10.3

### Operating system/version

Arch Linux

### Browser/version

Firefox 134.0.1

### Describe the bug

The Live page never loads and appears this on screen:

![Image](https://github.com/user-attachments/assets/8f6eafc1-64ef-454c-839b-0fec41ceb66c)

Sometimes it loads correctly, but instantly gets loading permanently

![Image](https://github.com/user-attachments/assets/96110e8c-c184-4e7d-8f59-40ee2d83aa3c)

### Steps To Reproduce

1. Open any HTML in nvim
2. Start LivePreview
3. Page does something strange

### Expected Behavior

Auto reload normaly

### Health

```help
livepreview: require("livepreview.health").check()

Check dependencies ~
- OK Nvim 0.10.3 is compatible with Live Preview
- OK `sh` is available
- WARNING `telescope` (optional) is not installed
- OK `fzf-lua` is installed
- WARNING `mini.pick` (optional) is not installed

Checkhealth server and process ~
- OK This Nvim process's PID is 8896
- OK Server is healthy on port 5500
- OK Server root: /home/cherry

Check your live-preview.nvim config ~
- {
    autokill = false,
    browser = "default",
    dynamic_root = false,
    port = 5500,
    sync_scroll = true
  }
```

### Repro

**lazy.lua**
```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  local lazyrepo = "https://github.com/folke/lazy.nvim.git"
  local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
  if vim.v.shell_error ~= 0 then
    vim.api.nvim_echo({
      { "Failed to clone lazy.nvim:\n", "ErrorMsg" },
      { out, "WarningMsg" },
      { "\nPress any key to exit..." },
    }, true, {})
    vim.fn.getchar()
    os.exit(1)
  end
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  spec = {
    -- add LazyVim and import its plugins
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- import/override with your plugins
    { import = "plugins" },
  },
  defaults = {
    -- By default, only LazyVim plugins will be lazy-loaded. Your custom plugins will load during startup.
    -- If you know what you're doing, you can set this to `true` to have all your custom plugins lazy-loaded by default.
    lazy = false,
    -- It's recommended to leave version=false for now, since a lot the plugin that support versioning,
    -- have outdated releases, which may break your Neovim install.
    version = false, -- always use the latest git commit
    -- version = "*", -- try installing the latest stable version for plugins that support semver
  },
  install = { colorscheme = { "catppuccin" } },
  checker = {
    enabled = true, -- check for plugin updates periodically
    notify = false, -- notify on update
  }, -- automatically check for plugin updates
  performance = {
    rtp = {
      -- disable some rtp plugins
      disabled_plugins = {
        "gzip",
        -- "matchit",
        -- "matchparen",
        -- "netrwPlugin",
        "tarPlugin",
        "tohtml",
        "tutor",
        "zipPlugin",
      },
    },
  },
})
```
**plugins.lua**
```lua
-- since this is just an example spec, don't actually load anything here and return an empty spec
-- stylua: ignore


-- every spec file under the "plugins" directory will be loaded automatically by lazy.nvim
--
-- In your plugin files, you can:
-- * add extra plugins
-- * disable/enabled LazyVim plugins
-- * override the configuration of LazyVim plugins
return {
{
  "LazyVim/LazyVim",
  opts = {
    colorscheme = "catppuccin",
  },
},
{
    'brianhuster/live-preview.nvim',
    dependencies = {
        'ibhagwan/fzf-lua',
    },
  },
}
```

**Comment by brianhuster** [comment]
Please provide a **minimal configuration**, save it in a file (eg. `repro.lua`) and try running it with `nvim -u repro.lua`

**Comment by BlackCherryCat** [comment]
I don't understand that part

**Comment by brianhuster** [comment]
It means a small configuration that only includes live-preview.nvim and nothing else, and then test that config. Lazyvim includes many plugins, some of them may affect live-preview.nvim so I need to rule out that possibility.

**Comment by BlackCherryCat** [comment]
same issue with repro:

![Image](https://github.com/user-attachments/assets/3b330ab6-b33c-4c4f-ac85-93b884588042)

**Comment by BlackCherryCat** [comment]
it must be the latest, but can you say me how can I check it?
My repro.lua:
```
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
	spec = {
		{
			"brianhuster/live-preview.nvim",
			config = function()
				require("live-preview").setup({
					-- Add your configuration here
				})
			end,
		},
	},
})
```

**Comment by BlackCherryCat** [comment]
now I have this every minute or so

![Image](https://github.com/user-attachments/assets/1a4a6238-31fa-4e91-b0cb-a2500aeb509c)

**Comment by brianhuster** [comment]
I have never encountered that error. But I have merged a patch that may fix that bug (not sure since I can't reproduce it)

Here are something else you should notice:

- Make sure that you exit Neovim and open it again after updating. 
- Clear browser cache.

**Comment by BlackCherryCat** [comment]
Every time I enter neovim fetches the plugin, I thins this is not a problem, but the issue persist even in chromium

**Comment by BlackCherryCat** [comment]
> now I have this every minute or so
> 
> ![Image](https://github.com/user-attachments/assets/1a4a6238-31fa-4e91-b0cb-a2500aeb509c)

I always get this error after just waiting, I didn't even edit anything in the document

**Comment by brianhuster** [comment]
Have you updated the plugin?

**Comment by BlackCherryCat** [comment]
how can I do it with nvim commands? I dont have ```:Lazy```

**Comment by brianhuster** [comment]
Just go to the plugin directory and run `git pull`. Or you can remove it and reinstall it with `git clone --depth=1 https://github.com/brianhuster/live-preview.nvim`

**Comment by BlackCherryCat** [comment]
same issue

![Image](https://github.com/user-attachments/assets/73ce34e5-ba26-4972-8b09-45a0704b43b2)

**Comment by brianhuster** [comment]
Still can't reproduce, can you send me a screencast video?

**Comment by brianhuster** [comment]
How is it like when you are running the server and you also run this script?
```vim
let s:count = 0
func! s:test()
  let s:count += 1
  echo 'Dir changed ' . s:count
endf
au User LivePreviewDirChanged call s:test
```

**Comment by BlackCherryCat** [comment]
Sorry, can you explain me how can I do that?

**Comment by brianhuster** [comment]
Yes. Run this command to open a new buffer
```vim
:e test.vim
```
Then copy that code to the buffer. Then run it with
```vim
:source test.vim
```

**Comment by BlackCherryCat** [comment]
Every time that the page spams those ```type:reload``` texts, the dir changes, according to your script.

![Image](https://github.com/user-attachments/assets/c477a48a-7389-45ad-bdc7-3b3578bfc1bc)

**btw, you missed the () in the last s:test function*

> au User LivePreviewDirChanged call s:test

**Comment by brianhuster** [comment]
1. Can you open `http://localhost:5500/live-preview.nvim/static/ws-client.js`. And send me screenshot for the whole page. 

2. I can't tell why LivePreviewDirChanged is triggered that much, maybe you should also use inotifytools to check it. Run this bash script
```bash
!/bin/bash
inotifywait -r -m -e modify,create,delete . | while read path action file; do
    echo "The file '$file' at '$path' was $action"
done
```

**Comment by brianhuster** [comment]
1. Can you open `http://localhost:5500/live-preview.nvim/static/ws-client.js`. And send me screenshot for the whole page. 

2. I can't tell why LivePreviewDirChanged is triggered that much, maybe you should also use inotifytools to check it. Run this bash script
```bash
!/bin/bash
inotifywait -r -m | while read path action file; do
    echo "The file '$file' at '$path' was $action"
done
```

**Comment by BlackCherryCat** [comment]
The ws-client.js:
```
const wsUrl = getWebSocketUrl();
let socket = new WebSocket(wsUrl);
let connected = true;

function getWebSocketUrl() {
	const protocol = window.location.protocol === "https:" ? "wss:" : "ws:";
	const hostname = window.location.hostname;
	const port = window.location.port ? `:${window.location.port}` : "";
	return `${protocol}//${hostname}${port}`;
}

/** 
 * Check if browser should handle websocket message from server
 * @param {string} filepath - The path of the file
 * @returns {boolean} - True if the browser should handle the message, false otherwise
 */
const isRightPath = (filepath) => {
	return filepath.includes(window.location.pathname.replace(/%20/g, " "));
}

let livepreview_reload

async function connectWebSocket() {
	socket = new WebSocket(wsUrl);

	socket.onopen = () => {
		if (!connected) {
			window.location.reload();
		}
		connected = true;
		console.log("Connected to server");
		console.log("connected: ", connected);
		livepreview_reload = 0;
	};

	socket.onmessage = (event) => {
		const message = JSON.parse(event.data);

		if (message.type === "reload") {
			console.log("Reload message received");
			if (livepreview_reload === 0) {
				livepreview_reload = 1;
				connected = false;
				socket.close();
				return;
			}
		} else if (message.type === "update") {
			console.log("Update message received");
			let { filepath, content } = message;
			if (isRightPath(filepath)) {
				// Check if the render function is defined before calling it
				if (typeof livepreview_render !== "undefined") {
					livepreview_render(content);
					if (typeof livepreview_renderKatex !== "undefined") {
						livepreview_renderKatex();
					}
					if (typeof livepreview_renderMermaid !== "undefined") {
						livepreview_renderMermaid();
					}
				} else {
					// Check if viewing svg
					if (window.location.pathname.endsWith(".svg")) {
						const livepreview_render = (text) => {
							document.querySelector('.markdown-body').innerHTML = text;
						}
						livepreview_render(content);
					}
					else {
						console.error("livepreview_render function is not defined");
					}
				}
			}
		} else if (message.type === "scroll") {
			console.log("Scroll message received");
			const { filepath, cursor } = message;
			if (isRightPath(filepath)) {
				const line = document.querySelector(`[data-source-line="${cursor[0]}"]`);
				if (line) {
					line.scrollIntoView({ behavior: "smooth", block: "center" });
				} else {
					// Find the closest line number
					const lineNumbers = document.querySelectorAll(".source-line");
					let closest = lineNumbers[0];
					let minDiff = Math.abs(cursor[0] - parseInt(closest.getAttribute("data-source-line")));
					lineNumbers.forEach((lineNumber) => {
						const diff = Math.abs(cursor[0] - parseInt(lineNumber.getAttribute("data-source-line")));
						if (diff < minDiff) {
							minDiff = diff;
							closest = lineNumber;
						}
					});
					closest.scrollIntoView({ behavior: "smooth", block: "center" });
				}
			}
		}
	};

	socket.onclose = () => {
		connected = false;
		console.log("Disconnected from server");
		window.location.reload();
	};

	socket.onerror = (error) => {
		console.error("WebSocket error:", error);
	};
}

window.onload = () => {
	connectWebSocket();
	setInterval(() => {
		if (!connected) {
			connectWebSocket();
		}
	}, 1000);
};

```

**Comment by brianhuster** [comment]
What about the bash script?

**Comment by BlackCherryCat** [comment]
Okay I found something interesting while testing your bash script, I've discovered that if my current working directory is my home LivePreview goes crazy (have to say that when I executed the bash script there's a lot of folders and files that changes inside the home directory, most of the time in .local/share, many files moves in there because of steam), because while testing it I dropped all the files I am using (repro.lua, html file, etc) into a folder, and the issue dissapears, it becomes responsive and doesn't drop any `reload` text.
I have to say that Lazyvim comes with a project manager, so I usually just run nvim in my home directory (the default directory when you open the terminal) and with the project manager jump into the folder that contains all my files.
EX:

![Image](https://github.com/user-attachments/assets/e28349c6-5efa-43de-bf31-136b11d2effc)

![Image](https://github.com/user-attachments/assets/d5cf966f-dd61-4c2d-a339-b46996191985)
As you can see here I have the list of my projects, and when I choose any of them It's like I'm that location

![Image](https://github.com/user-attachments/assets/9e922ab7-4bf6-41ff-a821-6b9b2d1ba1d5)
But when I exit neovim I'm in my home directory, so the thing is (and from what I see), there is a way to make LivePreview ignore all the things happen in my folders of my home folder?
